class ErrorCode:
    SUCCESS = "SUCCESS"

    INVALID_QUERY = "INVALID_QUERY"
    AGENT_EXECUTION_ERROR = "AGENT_EXECUTION_ERROR"
    RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
    LLM_ERROR = "LLM_ERROR"
    SKILL_ERROR = "SKILL_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"