import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const [inputPath, outputPath, previewDir] = process.argv.slice(2);
if (!inputPath || !outputPath || !previewDir) throw new Error("Usage: node build_rag_rewrite_ab_report.mjs input output preview");
const r = JSON.parse(await fs.readFile(inputPath, "utf8")), wb = Workbook.create();
const navy="#1B3B63", blue="#DDEBF7", green="#E2F0D9", yellow="#FFF2CC", red="#FCE4D6";
function title(sh, range, text){sh.getRange(range).merge();sh.getRange(range.split(":")[0]).values=[[text]];sh.getRange(range).format={fill:navy,font:{bold:true,color:"#FFFFFF",size:16},rowHeight:28};sh.showGridLines=false}
function header(range){range.format={fill:navy,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",wrapText:true}}

const o=wb.worksheets.add("A-B总览");title(o,"A1:J1","BM25 原始查询 vs 确定性中英术语扩展（开发集）");
o.getRange("A3:J3").values=[["配置","Chunk Recall@1","Chunk Recall@3","Chunk Recall@5","MRR@5","nDCG@5","Page Recall@1","Page Recall@3","Page Recall@5","平均延迟ms"]];header(o.getRange("A3:J3"));
o.getRange("A4:J5").values=[["原始 BM25",r.baseline.recall_at_1,r.baseline.recall_at_3,r.baseline.recall_at_5,r.baseline.mrr_at_5,r.baseline.ndcg_at_5,r.baseline.page_recall_at_1,r.baseline.page_recall_at_3,r.baseline.page_recall_at_5,r.baseline.average_query_latency_ms],["术语扩展",r.candidate.recall_at_1,r.candidate.recall_at_3,r.candidate.recall_at_5,r.candidate.mrr_at_5,r.candidate.ndcg_at_5,r.candidate.page_recall_at_1,r.candidate.page_recall_at_3,r.candidate.page_recall_at_5,r.candidate.average_query_latency_ms]];o.getRange("B4:I5").format.numberFormat="0.00%";o.getRange("J4:J5").format.numberFormat="0.000";
o.getRange("A7:J7").merge();o.getRange("A7").values=[[`逐题结果：提升 ${r.outcomes.improved}，回归 ${r.outcomes.regressed}，不变 ${r.outcomes.unchanged}。Chunk Recall@5 提升 ${(r.comparison.recall_at_5.delta*100).toFixed(2)} 个百分点。`]];o.getRange("A7:J7").format={fill:green,font:{bold:true},wrapText:true,rowHeight:32};
o.getRange("A9:J9").merge();o.getRange("A9").values=[["重要边界：术语表参考了当前 16 题，因此这是开发集机制验证，不是生产晋升证据。必须在未参与术语设计的保留集上复测。"]];o.getRange("A9:J9").format={fill:yellow,font:{bold:true},wrapText:true,rowHeight:36};o.getRange("A:J").format.columnWidth=18;

const d=wb.worksheets.add("逐题对照");title(d,"A1:L1","16 题查询扩展与逐题净变化");d.getRange("A3:L3").values=[["用例","原问题","实际检索查询","命中术语","基线首排","候选首排","基线Chunk R@5","候选Chunk R@5","Chunk变化","Page变化","结论","说明"]];header(d.getRange("A3:L3"));
const rows=r.cases.map(x=>[x.id,x.question,x.search_query,x.rewrite_matches.map(m=>`${m.source}→${m.target}`).join("; "),x.baseline_first_rank,x.candidate_first_rank,x.baseline_recall_at_5,x.candidate_recall_at_5,x.chunk_recall_delta,x.page_recall_delta,x.outcome,x.outcome==="improved"?"精确证据进入Top5":x.outcome==="regressed"?"原命中丢失":"排名未跨越Top5门槛"]);d.getRangeByIndexes(3,0,rows.length,12).values=rows;d.getRange(`G4:J${rows.length+3}`).format.numberFormat="0.00%";d.getRange(`A4:L${rows.length+3}`).format.wrapText=true;d.getRange("A:A").format.columnWidth=22;d.getRange("B:B").format.columnWidth=42;d.getRange("C:C").format.columnWidth=70;d.getRange("D:D").format.columnWidth=42;d.getRange("L:L").format.columnWidth=28;d.freezePanes.freezeRows(3);
d.getRange(`K4:K${rows.length+3}`).conditionalFormats.add("containsText",{text:"improved",format:{fill:green}});d.getRange(`K4:K${rows.length+3}`).conditionalFormats.add("containsText",{text:"regressed",format:{fill:red}});

const t=wb.worksheets.add("术语表");title(t,"A1:D1","确定性中英术语表 v1");t.getRange("A3:D3").values=[["中文触发词","英文扩展","选择依据","风险"]];header(t.getRange("A3:D3"));const terms=Object.entries(r.term_map).map(([a,b])=>[a,b,"当前科研语料常用对应表达","仅字面包含触发；可能存在领域歧义"]);t.getRangeByIndexes(3,0,terms.length,4).values=terms;t.getRange(`A4:D${terms.length+3}`).format.wrapText=true;t.getRange("A:D").format.columnWidth=32;t.getRange("B:B").format.columnWidth=42;

const m=wb.worksheets.add("指标与决策");title(m,"A1:D1","指标口径、缺陷修复与下一步决策");m.getRange("A3:D3").values=[["项目","定义/结果","作用","边界"]];header(m.getRange("A3:D3"));m.getRange("A4:D11").values=[["Chunk Recall@5","精确金标准 Chunk 是否进入Top5","主检索质量指标","相邻Chunk不算命中"],["Page Recall@5","正确论文的正确PDF页是否进入Top5","诊断切分边界问题","仅作为辅助指标"],["去重规则","同一相关页只计首次命中","防止nDCG超过100%","Chunk主指标同样适用"],["查询扩展","保留原问题并追加命中英文术语","解决中英词汇鸿沟","不理解上下文语义"],["成本","0 LLM调用；仅规则匹配","稳定、便宜、可审计","术语维护有人力成本"],["逐题回归",`${r.outcomes.regressed}题`,"防止平均值掩盖损失","当前仅16题"],["评测角色",r.evaluation_role,"明确结论强度","不得据此生产晋升"],["下一步","建立未参与术语设计的保留集，再实现多语言Dense基线","区分规则拟合与泛化收益","保持相同PDF/Chunk/指标"]];m.getRange("A4:D11").format={wrapText:true,borders:{preset:"inside",style:"thin",color:"#D9E2F3"}};m.getRange("A:A").format.columnWidth=24;m.getRange("B:B").format.columnWidth=55;m.getRange("C:D").format.columnWidth=36;

for(const sh of wb.worksheets.items)sh.getUsedRange().format.font={name:"Microsoft YaHei"};await fs.mkdir(previewDir,{recursive:true});for(const sh of wb.worksheets.items){const p=await wb.render({sheetName:sh.name,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(path.join(previewDir,`${sh.name}.png`),new Uint8Array(await p.arrayBuffer()))}
console.log((await wb.inspect({kind:"table",range:"A-B总览!A1:J9",include:"values,formulas",tableMaxRows:12,tableMaxCols:12})).ndjson);console.log((await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100}})).ndjson);await fs.mkdir(path.dirname(outputPath),{recursive:true});const out=await SpreadsheetFile.exportXlsx(wb);await out.save(outputPath);console.log(outputPath);
