import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const [comparePath,coldPath,warmPath,output,previewDir]=process.argv.slice(2);
if(!previewDir) throw new Error("用法: node build_dense_cache_report.mjs compare cold warm output preview");
const c=JSON.parse(await fs.readFile(comparePath,"utf8")),cold=JSON.parse(await fs.readFile(coldPath,"utf8")),warm=JSON.parse(await fs.readFile(warmPath,"utf8"));
const wb=Workbook.create(),navy="#17365D",green="#E2F0D9",yellow="#FFF2CC",blue="#D9EAF7";
function title(s,r,t){s.getRange(r).merge();s.getRange(r.split(":")[0]).values=[[t]];s.getRange(r).format={fill:navy,font:{bold:true,color:"#FFFFFF",size:16},rowHeight:30};s.showGridLines=false}
function header(r){r.format={fill:navy,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",wrapText:true}}
const s=wb.worksheets.add("缓存评测总览");title(s,"A1:F1","Dense 向量缓存冷启动 / 热启动对比");
s.getRange("A3:F3").values=[["阶段","缓存命中","缓存读取(ms)","检索器构造(ms)","缓存写入(ms)","说明"]];header(s.getRange("A3:F3"));
s.getRange("A4:F5").values=[["冷启动",cold.cache.hit,cold.timing.cache_load_ms,cold.timing.index_build_ms,cold.timing.cache_write_ms,"首次编码 1098 个 Chunk 并写入缓存"],["热启动",warm.cache.hit,warm.timing.cache_load_ms,warm.timing.index_build_ms,warm.timing.cache_write_ms,"读取已有向量，不再编码论文全文"]];s.getRange("C4:E5").format.numberFormat="0.000";
s.getRange("A7:D7").values=[["判定指标","结果","门槛","含义"]];header(s.getRange("A7:D7"));
s.getRange("A8:D12").values=[["指纹一致",c.cache.fingerprint_equal,true,"冷/热运行对应同一语料与配置"],["质量完全一致",c.quality_equal,true,"Recall、MRR、nDCG 未被缓存改变"],["建库耗时下降",c.timing.index_build_reduction_pct/100,0.99,"热启动构造耗时至少下降 99%"],["缓存验证通过",c.decision.cache_validated,true,"同时满足命中、质量与速度条件"],["生产 Dense 默认",c.decision.production_default,false,"缓存通过不等于检索模型通过"]];s.getRange("B10:C10").format.numberFormat="0.0000%";s.getRange("A14:F15").merge();s.getRange("A14").values=[["结论：缓存把重复建库阶段从 61.62 秒降到约 13.57ms（读取 + 构造），但每个查询仍需实时生成 Embedding。缓存能力通过专项验证，Dense 模型生产开关继续关闭。"]];s.getRange("A14:F15").format={fill:green,font:{bold:true},wrapText:true,verticalAlignment:"center"};s.getRange("A:F").format.columnWidth=22;s.getRange("F:F").format.columnWidth=48;
const q=wb.worksheets.add("质量不变验证");title(q,"A1:F1","缓存前后检索质量一致性");q.getRange("A3:F3").values=[["数据集","指标","冷启动","热启动","变化","结果"]];header(q.getRange("A3:F3"));
const names={recall_at_5:"Chunk Recall@5",mrr_at_5:"MRR@5",ndcg_at_5:"nDCG@5",page_recall_at_5:"Page Recall@5",page_ndcg_at_5:"Page nDCG@5"},rows=[];for(const [key,label] of [["development","开发集"],["holdout","独立保留集"]])for(const [metric,name] of Object.entries(names)){const a=cold[key].summary[metric],b=warm[key].summary[metric];rows.push([label,name,a,b,b-a,a===b?"一致":"变化"])}q.getRangeByIndexes(3,0,rows.length,6).values=rows;q.getRange(`C4:E${rows.length+3}`).format.numberFormat="0.00%";q.getRange("A:F").format.columnWidth=22;q.getRange("F:F").conditionalFormats.add("containsText",{text:"一致",format:{fill:green}});
const d=wb.worksheets.add("缓存契约与风险");title(d,"A1:D1","缓存指纹、失效与安全边界");d.getRange("A3:D3").values=[["检查项","实现","为什么需要","失败风险"]];header(d.getRange("A3:D3"));d.getRange("A4:D10").values=[["语料身份","document_id、chunk_id、页码、字符位置、全文","确认向量与当前 Chunk 一一对应","返回错误证据且难以追踪"],["处理版本","Parser 与 Chunker 名称和版本","切分变化必须重建","新文本复用旧向量"],["模型身份","完整模型名","不同 Embedding 空间不可混用","余弦分数失真"],["缓存格式","cache_version","格式升级可主动失效","旧结构读取异常"],["安全加载","allow_pickle=false","不执行缓存内任意 Python 对象","不可信缓存带来代码执行风险"],["原子写入","临时文件后 os.replace","避免中断留下半写文件","下次启动读取损坏向量"],["生产边界","production_default=false","缓存性能通过不代表模型质量通过","绕过逐题回归门槛"]];d.getRange("A4:D10").format.wrapText=true;d.getRange("A:A").format.columnWidth=20;d.getRange("B:D").format.columnWidth=45;d.getRange("A12:D13").merge();d.getRange("A12").values=[[`缓存指纹：${warm.cache.fingerprint}`]];d.getRange("A12:D13").format={fill:blue,wrapText:true};
const n=wb.worksheets.add("下一步");title(n,"A1:D1","后续稳定性评测计划");n.getRange("A3:D3").values=[["顺序","工作","记录指标","目的"]];header(n.getRange("A3:D3"));n.getRange("A4:D7").values=[[1,"多次独立进程热启动","模型加载、缓存读取、构造、平均/P95 查询耗时","量化运行波动"],[2,"固定逐题排名一致性","Top-5 Chunk、分数、Recall/MRR/nDCG","确认确定性"],[3,"第二个多语言 Dense 单变量对照","相同语料、标注、Chunker、指标","避免写死 MiniLM"],[4,"Dense + BM25 Hybrid","质量、回归、延迟与存储","判断是否互补"]];n.getRange("A4:D7").format.wrapText=true;n.getRange("A:A").format.columnWidth=12;n.getRange("B:D").format.columnWidth=46;n.getRange("A9:D10").merge();n.getRange("A9").values=[["下一步只做重复运行稳定性；在结果稳定前不进入第二模型，也不修改生产检索路径。"]];n.getRange("A9:D10").format={fill:yellow,font:{bold:true},wrapText:true};
for(const sh of wb.worksheets.items)sh.getUsedRange().format.font={name:"Microsoft YaHei",size:10};await fs.mkdir(previewDir,{recursive:true});for(const sh of wb.worksheets.items){const p=await wb.render({sheetName:sh.name,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(path.join(previewDir,`${sh.name}.png`),new Uint8Array(await p.arrayBuffer()))}console.log((await wb.inspect({kind:"table",range:"缓存评测总览!A1:F15",include:"values,formulas",tableMaxRows:20,tableMaxCols:8})).ndjson);console.log((await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100}})).ndjson);await fs.mkdir(path.dirname(output),{recursive:true});const x=await SpreadsheetFile.exportXlsx(wb);await x.save(output);console.log(output);
