import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
const input=process.argv[2]??"eval_harness/reports/retrieval_replan_eval.json", output=process.argv[3]??"outputs/replan_comparison/replan_comparison_report.xlsx", previewDir=process.argv[4]??"outputs/replan_comparison/previews";
const r=JSON.parse(await fs.readFile(input,"utf8")), s=r.summary, wb=Workbook.create(); const navy="#1B3B63",green="#E2F0D9",yellow="#FFF2CC",blue="#DDEBF7";
function title(sh,rg,t){sh.getRange(rg).merge();sh.getRange(rg.split(":")[0]).values=[[t]];sh.getRange(rg).format={fill:navy,font:{bold:true,color:"#FFFFFF",size:16},rowHeight:28};sh.showGridLines=false} function header(rg){rg.format={fill:navy,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center",borders:{preset:"inside",style:"thin",color:"#FFFFFF"}}}
const o=wb.worksheets.add("对照总览");title(o,"A1:H1","PaperAgent 普通重试 vs Retrieval Replan v1");o.getRange("A3:H3").values=[["案例数","分类准确率","普通恢复率","Replan恢复率","提升百分点","普通无效重试","Replan无效重试","门槛"]];header(o.getRange("A3:H3"));o.getRange("A4:H4").values=[[s.case_count,s.classification_accuracy_pct/100,s.baseline_recovery_rate_pct/100,s.candidate_recovery_rate_pct/100,s.recovery_rate_delta_pct_points/100,s.baseline_ineffective_retry_rate_pct/100,s.candidate_ineffective_retry_rate_pct/100,s.acceptance_passed?"通过":"不通过"]];o.getRange("B4:G4").format.numberFormat="0.0%";o.getRange("A6:H6").merge();o.getRange("A6").values=[["结论：Replan v1 在固定故障集上达到分类、恢复和无效重试门槛，且不增加 LLM 调用；阶段收口。"]];o.getRange("A6:H6").format={fill:green,font:{bold:true},wrapText:true,rowHeight:32};o.getRange("A8:H8").merge();o.getRange("A8").values=[["边界：恢复由模拟成功查询判定，不代表真实线上恢复率。下一阶段处理第二轮结果反馈与停止原因。"]];o.getRange("A8:H8").format={fill:yellow,wrapText:true,rowHeight:34};o.getRange("A:H").format.columnWidth=18;
const c=wb.worksheets.add("逐例对照");title(c,"A1:J1","固定故障集逐例对照");c.getRange("A3:J3").values=[["案例","预期类型","实际类型","动作","普通查询","Replan查询","分类通过","普通恢复","Replan恢复","普通无效重试"]];header(c.getRange("A3:J3"));const rows=r.cases.map(x=>[x.id,x.expected_failure_type,x.actual_failure_type,x.action,x.baseline_query,x.candidate_query,x.classification_passed,x.baseline_recovered,x.candidate_recovered,x.baseline_ineffective_retry]);c.getRangeByIndexes(3,0,rows.length,10).values=rows;c.getRange("A:J").format.columnWidth=20;c.getRange("E:F").format.columnWidth=36;c.freezePanes.freezeRows(3);
const m=wb.worksheets.add("指标口径");title(m,"A1:D1","指标计算口径与限制");m.getRange("A3:D3").values=[["指标","计算方法","门槛","限制"]];header(m.getRange("A3:D3"));m.getRange("A4:D8").values=[["分类准确率","分类正确数 ÷ 总案例数","100%","固定的三类故障"],["恢复率","第二轮查询等于案例定义的成功查询数 ÷ 总案例数","Replan >=80%","模拟成功条件"],["恢复增益","Replan恢复率 - 普通恢复率",">=40个百分点","不代表真实 API 命中率"],["无效重试率","语义失败中查询未改变的比例","Replan=0","暂时工具失败允许原查询重试"],["LLM调用","评测与 Replan 新增调用数","0","只覆盖确定性 v1"]];m.getRange("A4:D8").format={wrapText:true,borders:{preset:"inside",style:"thin",color:"#D9E2F3"}};m.getRange("A:D").format.columnWidth=34;m.getRange("B:B").format.columnWidth=48;m.getRange("A10:D10").merge();m.getRange("A10").values=[["下一阶段：第二轮质量仍不足时必须记录预算耗尽和停止原因，之后才考虑 Reflection/Reflexion。"]];m.getRange("A10:D10").format={fill:blue,font:{bold:true},wrapText:true,rowHeight:34};
for(const n of ["对照总览","逐例对照","指标口径"]){wb.worksheets.getItem(n).getUsedRange().format.font={name:"Microsoft YaHei"}}await fs.mkdir(previewDir,{recursive:true});for(const n of ["对照总览","逐例对照","指标口径"]){const p=await wb.render({sheetName:n,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(`${previewDir}/${n}.png`,new Uint8Array(await p.arrayBuffer()))}console.log((await wb.inspect({kind:"table",range:"对照总览!A1:H8",include:"values,formulas",tableMaxRows:10,tableMaxCols:10})).ndjson);console.log((await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100}})).ndjson);await fs.mkdir(output.split(/[\\/]/).slice(0,-1).join("/"),{recursive:true});const x=await SpreadsheetFile.exportXlsx(wb);await x.save(output);console.log(output);
